// Code generated by protoc-gen-go. DO NOT EDIT.
// source: faild.proto

package faild

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_39a821ccc5c5d331, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Status struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_39a821ccc5c5d331, []int{1}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Stats struct {
	Stats                map[string]int64 `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Stats) Reset()         { *m = Stats{} }
func (m *Stats) String() string { return proto.CompactTextString(m) }
func (*Stats) ProtoMessage()    {}
func (*Stats) Descriptor() ([]byte, []int) {
	return fileDescriptor_39a821ccc5c5d331, []int{2}
}

func (m *Stats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stats.Unmarshal(m, b)
}
func (m *Stats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stats.Marshal(b, m, deterministic)
}
func (m *Stats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stats.Merge(m, src)
}
func (m *Stats) XXX_Size() int {
	return xxx_messageInfo_Stats.Size(m)
}
func (m *Stats) XXX_DiscardUnknown() {
	xxx_messageInfo_Stats.DiscardUnknown(m)
}

var xxx_messageInfo_Stats proto.InternalMessageInfo

func (m *Stats) GetStats() map[string]int64 {
	if m != nil {
		return m.Stats
	}
	return nil
}

type InitRequest struct {
	VIP                  string   `protobuf:"bytes,1,opt,name=VIP,proto3" json:"VIP,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitRequest) Reset()         { *m = InitRequest{} }
func (m *InitRequest) String() string { return proto.CompactTextString(m) }
func (*InitRequest) ProtoMessage()    {}
func (*InitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_39a821ccc5c5d331, []int{3}
}

func (m *InitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitRequest.Unmarshal(m, b)
}
func (m *InitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitRequest.Marshal(b, m, deterministic)
}
func (m *InitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitRequest.Merge(m, src)
}
func (m *InitRequest) XXX_Size() int {
	return xxx_messageInfo_InitRequest.Size(m)
}
func (m *InitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitRequest proto.InternalMessageInfo

func (m *InitRequest) GetVIP() string {
	if m != nil {
		return m.VIP
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "faild.Empty")
	proto.RegisterType((*Status)(nil), "faild.Status")
	proto.RegisterType((*Stats)(nil), "faild.Stats")
	proto.RegisterMapType((map[string]int64)(nil), "faild.Stats.StatsEntry")
	proto.RegisterType((*InitRequest)(nil), "faild.InitRequest")
}

func init() { proto.RegisterFile("faild.proto", fileDescriptor_39a821ccc5c5d331) }

var fileDescriptor_39a821ccc5c5d331 = []byte{
	// 275 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x41, 0x4b, 0xfb, 0x40,
	0x10, 0xc5, 0xbb, 0x4d, 0xb6, 0xa5, 0x93, 0x14, 0xfe, 0x0c, 0x7f, 0x30, 0xf4, 0x62, 0x58, 0x50,
	0x02, 0xd2, 0x1e, 0x2a, 0x48, 0xf1, 0x5e, 0x25, 0xb7, 0xb2, 0x81, 0xde, 0x63, 0xba, 0x4a, 0xb0,
	0x6d, 0x62, 0x76, 0x52, 0xc8, 0x47, 0xf3, 0xdb, 0xc9, 0xee, 0xb6, 0x18, 0xf4, 0xe0, 0x65, 0x99,
	0xb7, 0xf3, 0x7e, 0xbc, 0xd9, 0x59, 0x08, 0x5e, 0xf3, 0x72, 0xbf, 0x5b, 0xd4, 0x4d, 0x45, 0x15,
	0x72, 0x2b, 0xc4, 0x18, 0xf8, 0xfa, 0x50, 0x53, 0x27, 0x1e, 0x60, 0x94, 0x51, 0x4e, 0xad, 0x46,
	0x04, 0xbf, 0xa8, 0x76, 0x2a, 0x62, 0x31, 0x4b, 0xb8, 0xb4, 0x35, 0x46, 0x30, 0x3e, 0x28, 0xad,
	0xf3, 0x37, 0x15, 0x0d, 0x63, 0x96, 0x4c, 0xe4, 0x45, 0x8a, 0x1a, 0xb8, 0xe1, 0x34, 0xce, 0x81,
	0x6b, 0x53, 0x44, 0x2c, 0xf6, 0x92, 0x60, 0x79, 0xb5, 0x70, 0x69, 0xb6, 0xe9, 0xce, 0xf5, 0x91,
	0x9a, 0x4e, 0x3a, 0xd7, 0x6c, 0x05, 0xf0, 0x7d, 0x89, 0xff, 0xc0, 0x7b, 0x57, 0x9d, 0x8d, 0x9c,
	0x48, 0x53, 0xe2, 0x7f, 0xe0, 0xa7, 0x7c, 0xdf, 0xba, 0x3c, 0x4f, 0x3a, 0xf1, 0x38, 0x5c, 0x31,
	0x71, 0x0d, 0x41, 0x7a, 0x2c, 0x49, 0xaa, 0x8f, 0x56, 0x69, 0x32, 0xe8, 0x36, 0xdd, 0x5c, 0xd0,
	0x6d, 0xba, 0x59, 0x7e, 0x32, 0x08, 0x9f, 0x4c, 0x78, 0xa6, 0x9a, 0x53, 0x59, 0x28, 0xbc, 0x03,
	0xdf, 0x10, 0x88, 0xe7, 0x99, 0x7a, 0xf8, 0x6c, 0xda, 0x9b, 0xb3, 0xd5, 0x62, 0x80, 0xb7, 0xf6,
	0x41, 0x0d, 0x61, 0x78, 0xee, 0xd8, 0xfd, 0xfc, 0xf6, 0xdd, 0x80, 0x9f, 0x51, 0x55, 0xff, 0x65,
	0x9b, 0xc3, 0xf4, 0x59, 0x91, 0x91, 0xa5, 0xa6, 0xb2, 0xd0, 0x3f, 0xfc, 0x61, 0x7f, 0x4d, 0x62,
	0xf0, 0x32, 0xb2, 0xbf, 0x73, 0xff, 0x15, 0x00, 0x00, 0xff, 0xff, 0xe0, 0x76, 0x60, 0x49, 0xac,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FaildServiceClient is the client API for FaildService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FaildServiceClient interface {
	Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*Status, error)
	Start(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Status, error)
	Stop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Status, error)
	GetStatistics(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Stats, error)
}

type faildServiceClient struct {
	cc *grpc.ClientConn
}

func NewFaildServiceClient(cc *grpc.ClientConn) FaildServiceClient {
	return &faildServiceClient{cc}
}

func (c *faildServiceClient) Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/faild.FaildService/Init", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faildServiceClient) Start(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/faild.FaildService/Start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faildServiceClient) Stop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/faild.FaildService/Stop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faildServiceClient) GetStatistics(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Stats, error) {
	out := new(Stats)
	err := c.cc.Invoke(ctx, "/faild.FaildService/GetStatistics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FaildServiceServer is the server API for FaildService service.
type FaildServiceServer interface {
	Init(context.Context, *InitRequest) (*Status, error)
	Start(context.Context, *Empty) (*Status, error)
	Stop(context.Context, *Empty) (*Status, error)
	GetStatistics(context.Context, *Empty) (*Stats, error)
}

// UnimplementedFaildServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFaildServiceServer struct {
}

func (*UnimplementedFaildServiceServer) Init(ctx context.Context, req *InitRequest) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Init not implemented")
}
func (*UnimplementedFaildServiceServer) Start(ctx context.Context, req *Empty) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (*UnimplementedFaildServiceServer) Stop(ctx context.Context, req *Empty) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (*UnimplementedFaildServiceServer) GetStatistics(ctx context.Context, req *Empty) (*Stats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatistics not implemented")
}

func RegisterFaildServiceServer(s *grpc.Server, srv FaildServiceServer) {
	s.RegisterService(&_FaildService_serviceDesc, srv)
}

func _FaildService_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaildServiceServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/faild.FaildService/Init",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaildServiceServer).Init(ctx, req.(*InitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FaildService_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaildServiceServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/faild.FaildService/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaildServiceServer).Start(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _FaildService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaildServiceServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/faild.FaildService/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaildServiceServer).Stop(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _FaildService_GetStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaildServiceServer).GetStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/faild.FaildService/GetStatistics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaildServiceServer).GetStatistics(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _FaildService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "faild.FaildService",
	HandlerType: (*FaildServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Init",
			Handler:    _FaildService_Init_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _FaildService_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _FaildService_Stop_Handler,
		},
		{
			MethodName: "GetStatistics",
			Handler:    _FaildService_GetStatistics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "faild.proto",
}
